### PR TITLE
DT-1055 - Added change to ECS task definitions for test env

### PR DESCRIPTION
**Pull request by kierangarside09**
**Description** 
Added change to ECS task definitions for test env

**Local testing** 
N/A

**Release** 
N/A

### CODE REVIEW

**Review by hugh-emerson — CHANGES_REQUESTED** [review]
I don't know where that /bin folder came from, but you should remove it from your commit and then add it to the .gitignore file if it's being generated by your IDE or something.

`git rm --cached foobar` lets you "delete" files from git without deleting them from your filesystem if you want.

**Comment by keithkennedy** [comment]
May be worth using squash merge for this one so all the bin files don't end up in the history for `main`

**Comment by kierangarside09** [comment]
> May be worth using squash merge for this one so all the bin files don't end up in the history for `main`

I have no clue how to do that

**Review by hugh-emerson — APPROVED** [review]
Also I've tested this, so you can go ahead and apply this to production whenever you're ready. Happy to take a look at the terraform plan if you're unsure about anything.

**Comment by hugh-emerson** [comment]
The warning emails from AWS about us using the outdated option only get sent monthly. So we'll find out in September if this wasn't sufficient.

**Comment by kierangarside09** [comment]
@hugh-emerson Grand hugh thank you, I'm going to leave this PR open and add the changes to this

**Pull request merged**
